[whisper]
provider = "groq"
model = "whisper-large-v3-turbo"
language = "en"

[behavior]
auto_paste = true
delete_audio_files = true
audio_feedback = true

[ui.waybar]
idle_text = "󰓃"
recording_text = "󰻃"
